Repository openedx/frontend-app-communications, pull requests merged in 2024-02, with the labels that each got.

#154 fix: Added maxLength and default tip for email subject
  src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
  src/components/bulk-email-tool/bulk-email-form/messages.js
Labels: open-source-contribution, waiting for eng review

#192 fix: hardcoded course mode checkboxes
  src/components/bulk-email-tool/BulkEmailTool.jsx
  src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
  src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/BulkEmailRecipient.jsx
  src/components/bulk-email-tool/bulk-email-form/data/__factories__/bulkEmailFormCourseMode.factory.js
  src/components/bulk-email-tool/bulk-email-form/test/BulkEmailForm.test.jsx
  src/components/page-container/PageContainer.jsx
Labels: open-source-contribution, waiting for eng review, backport

#196 fix: limit email subject length
  src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
  src/components/bulk-email-tool/bulk-email-form/messages.js
Labels: open-source-contribution
