Repository openedx/frontend-app-communications, pull requests merged in 2025-04, with the labels that each got.

#220 chore: remove husky 🪓🐶
  package-lock.json
  package.json
Labels: open-source-contribution

#219 feat: upgrade to react 18
  package-lock.json
  package.json
  src/__snapshots__/index.test.jsx.snap
  src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailContentHistory.test.jsx
  src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailTaskHistory.test.jsx
  src/components/page-container/test/PageContainer.test.jsx
  src/index.jsx
  src/index.test.jsx
Labels: create-sandbox

#217 feat: support design tokens and paragon 23
  .env
  .env.development
  .env.test
  package-lock.json
  package.json
  src/index.scss
  src/setupTest.js
Labels: open-source-contribution, create-sandbox

#226 feat: import `FooterSlot` from component package instead of slot package
  .gitignore
  package-lock.json
  package.json
  src/components/page-container/PageContainer.jsx
  src/plugin-slots/FooterSlot/README.md
  src/plugin-slots/README.md
Labels: create-sandbox
